### ISSUE TITLE
Síntesis Gestión de Proyectos de Software.

### ISSUE THREAD

**Issue by ThorSampy** [SistemasTecTlaxiaco/sintesis-ThorSampy#2]
[Gestion de proyectos de software.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-ThorSampy/files/7151019/Gestion.de.proyectos.de.software.pdf)

**Comment by CarlosSD16** [comment]
Revisado calificación=20% aborda todos los temas vistos en el video y siguió un orden para el desarrollo del trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
